name: gestionnairebloc
description: Password manager with Bloc pattern
publish_to: "none"

version: 0.0.1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rename_app: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  build_runner: ^2.4.11
  hive_generator: ^2.0.0
  go_router: ^8.0.3
  flutter_secure_storage: ^8.0.0
  postgres: ^2.6.1
  encrypt: ^5.0.1
  path: ^1.8.3
  sqflite: ^2.2.8+4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - "assets/"

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/ubuntu/Ubuntu-R.ttf
        - asset: assets/ubuntu/Ubuntu-RI.ttf
          style: italic
        - asset: assets/ubuntu/Ubuntu-B.ttf
          weight: 700
        - asset: assets/ubuntu/Ubuntu-BI.ttf
          weight: 700
          style: italic
        - asset: assets/ubuntu/Ubuntu-L.ttf
          weight: 300
        - asset: assets/ubuntu/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: assets/ubuntu/Ubuntu-M.ttf
          weight: 500
        - asset: assets/ubuntu/Ubuntu-MI.ttf
          weight: 500
          style: italic
    - family: Ubuntu Mono
      fonts:
        - asset: assets/ubuntu/UbuntuMono-R.ttf
        - asset: assets/ubuntu/UbuntuMono-RI.ttf
          style: italic
        - asset: assets/ubuntu/UbuntuMono-B.ttf
          weight: 700
        - asset: assets/ubuntu/UbuntuMono-BI.ttf
          weight: 700
          style: italic
    - family: Ubuntu Condensed
      fonts:
        - asset: assets/ubuntu/Ubuntu-C.ttf
  uses-material-design: true
